version: "3.1"

services:
  wordpress:
    image: wordpress
    ports:
      - 8886:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./:/var/www/html/wp-content/plugins/advanced-rich-text-tools

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
